### ISSUE TITLE
deno 1.7.5 isolatedModules

### ISSUE THREAD

**Issue by beckend** [jurassiscripts/velociraptor#42]
```shell
Uncaught (in promise) TypeError: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ScriptsConfiguration } from "./src/scripts_config.ts";
         ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/velociraptor@1.0.0-beta.16/mod.ts:1:10
```

Then tried to use a custom tsconfig.json with:
```json
{
  "compilerOptions": {
    "importsNotUsedAsValues": "remove",
    "isolatedModules": false
  }
}
```

Running:
```shell
Unsupported compiler options in "/home/admin/.deno/bin/vr.tsconfig.json".
  The following options were ignored:
    isolatedModules
error: Uncaught (in promise) TypeError: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ScriptsConfiguration } from "./src/scripts_config.ts";
         ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/velociraptor@1.0.0-beta.16/mod.ts:1:10
```

**Comment by umbopepato** [comment]
Hey @beckend, thank you for the report and PR! Can I just ask you what OS are you using and the steps to reproduce this error?

**Comment by beckend** [comment]
I am using Arch Linux:

```shell
$ deno --version
deno 1.7.5 (release, x86_64-unknown-linux-gnu)
v8 9.0.123
typescript 4.1.4

$ deno install -qA -n vr https://x.nest.land/velociraptor@1.0.0-beta.16/cli.ts
✅ Successfully installed vr
$HOME/.deno/bin/vr

$ vr --version
1.0.0-beta.16
```

velociraptor.ts:
```typescript
import { ScriptsConfiguration } from 'https://deno.land/x/velociraptor@1.0.0-beta.16/cli.ts'

export default <ScriptsConfiguration>{
  scripts: {
    test: {
      cmd: 'deno test -A --coverage --unstable',
    },
  },
}
```

```shell
$ vr test
```
And the rest is described in the first post.
